export const tem1_1 = {
  stage: {
    attrs: {
      width: 1300,
      height: 900,
      x: 0,
      y: 0,
    },
    filters: [],
    className: "Stage",
  },
  layer: {
    attrs: {
      x: 0,
      y: 0,
      width: 1300,
      height: 900,
    },
    filters: [],
    className: "Layer",
  },
  background: {
    image: {
      attrs: {
        url: "http://localhost:3000/asserts/editor/background1.png",
        x: 0,
        y: 0,
        width: 1300,
        height: 900,
      },
      filters: [],
      className: "Image",
      zIndex: 1,
    },
    overlay: {
      attrs: {
        width: 1300,
        height: 900,
        x: 0,
        y: 0,
      },
      filters: [],
      className: "Rect",
      zIndex: 2,
    },
  },
  shapes: [
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [200, 200, 1100, 200],
        name: "guide",
        stroke: "#fa0000",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 900,
      },
      filters: [],
      className: "Line",
      zIndex: 3,
    },
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [200, 700, 1100, 700],
        name: "guide",
        stroke: "#15ff00",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 900,
      },
      filters: [],
      className: "Line",
      zIndex: 4,
    },
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [224, 225, 1074, 225],
        name: "guide",
        stroke: "#123",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 850,
      },
      filters: [],
      className: "Line",
      zIndex: 5,
    },
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [224, 675, 1074, 675],
        name: "guide",
        stroke: "#4c00ff",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 850,
      },
      filters: [],
      className: "Line",
      zIndex: 6,
    },
    {
      attrs: {
        x: 200,
        y: 200,
        width: 900,
        height: 500,
        fill: "#fff",
        name: "bgc",
        hitStrokeWidth: 0,
      },
      filters: [],
      className: "Rect",
      zIndex: 0,
    },
    {
      attrs: {
        x: 590,
        y: 291,
        width: 120,
        height: 40,
      },
      filters: [],
      className: "Label",
      zIndex: 11,
      children: [
        {
          attrs: {
            width: 120,
            height: 40,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "김태균",
            fill: "#000",
            fontSize: 40,
            fontFamily: "고딕",
            height: "auto",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        x: 534,
        y: 331,
        scaleY: 1.000000000000003,
        width: 232.16,
        height: 32,
      },
      filters: [],
      className: "Label",
      zIndex: 12,
      children: [
        {
          attrs: {
            width: 232.15625000000065,
            height: 32,
            scaleX: 1.000000000000003,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "Tae Kyun . Kim",
            fill: "#000",
            fontSize: "32",
            fontFamily: "굴림",
            height: "auto",
            width: 232.15625000000065,
            scaleX: 1.000000000000003,
            align: "center",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        x: 531,
        y: 377,
        width: 237.57,
        height: 18,
      },
      filters: [],
      className: "Label",
      zIndex: 13,
      children: [
        {
          attrs: {
            width: 237.568359375,
            height: 18,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "컨텐츠운영본부 / 감독 / 부장",
            fill: "rgba(208,2,27,1)",
            fontSize: "18",
            fontFamily: "고딕",
            height: "auto",
            align: "center",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        type: "shape",
        x: 650.08,
        y: 418.13,
        radius: 50,
        fill: "rgba(208,2,27,1)",
        scaleX: 0.18635642126551044,
        scaleY: 0.18635642126551097,
        skewX: -2.407412430484527e-30,
        width: 100,
        height: 100,
      },
      filters: [],
      className: "Circle",
      zIndex: 14,
    },
    {
      attrs: {
        type: "shape",
        x: 198.08,
        y: 600,
        width: 100,
        height: 100,
        fill: "rgba(208,2,27,1)",
        scaleX: 9.040000000000042,
        scaleY: 0.9999999999999947,
      },
      filters: [],
      className: "Rect",
      zIndex: 15,
    },
    {
      attrs: {
        x: 354,
        y: 450,
        width: 236.2,
        height: 32,
      },
      filters: [],
      className: "Label",
      zIndex: 17,
      children: [
        {
          attrs: {
            width: 236.203125,
            height: 32,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "T 070.1234.5678",
            fill: "#000",
            fontSize: "32",
            fontFamily: "고딕",
            height: "auto",
            align: "center",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        x: 640.76,
        y: 450,
        width: 348.3,
        height: 32,
      },
      filters: [],
      className: "Label",
      zIndex: 18,
      children: [
        {
          attrs: {
            width: 348.296875,
            height: 32,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "E snowwhite@daum.net",
            fill: "#000",
            fontSize: "32",
            fontFamily: "고딕",
            height: "auto",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        x: 407,
        y: 494,
        width: 248.47,
        height: 32,
      },
      filters: [],
      className: "Label",
      zIndex: 19,
      children: [
        {
          attrs: {
            width: 248.46875,
            height: 32,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "M 010.1234.5678",
            fill: "#000",
            fontSize: "32",
            fontFamily: "고딕",
            height: "auto",
            align: "center",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        x: 693.62,
        y: 494,
        width: 217.45,
        height: 32,
      },
      filters: [],
      className: "Label",
      zIndex: 20,
      children: [
        {
          attrs: {
            width: 217.453125,
            height: 32,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "F 031.123.4567",
            fill: "#000",
            fontSize: "32",
            fontFamily: "고딕",
            height: "auto",
            align: "center",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        x: 349.08,
        y: 540,
        width: 576.94,
        height: 32,
      },
      filters: [],
      className: "Label",
      zIndex: 21,
      children: [
        {
          attrs: {
            width: 576.9375,
            height: 32,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "A 경기도 고양시 일산동구 장대길 42-13 (장항동)",
            fill: "#000",
            fontSize: "32",
            fontFamily: "고딕",
            height: "auto",
            align: "center",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        x: 205.08,
        y: 620,
        scaleY: 0.9999999999999989,
        width: 889.18,
        height: 40,
      },
      filters: [],
      className: "Label",
      zIndex: 22,
      children: [
        {
          attrs: {
            width: 889.1835937500008,
            height: 40,
            scaleX: 0.9999999999999989,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "DIGITAL EVOLUTION",
            fill: "rgba(255,255,255,1)",
            fontSize: 40,
            fontFamily: "고딕",
            height: "auto",
            width: 889.1835937500008,
            scaleX: 0.9999999999999989,
            align: "center",
          },
          className: "Text",
        },
      ],
    },
  ],
};

export const tem1_2 = {
  stage: {
    attrs: {
      width: 1300,
      height: 900,
      x: 0,
      y: 0,
    },
    filters: [],
    className: "Stage",
  },
  layer: {
    attrs: {
      x: 0,
      y: 0,
      width: 1300,
      height: 900,
    },
    filters: [],
    className: "Layer",
  },
  background: {
    image: {
      attrs: {
        url: "http://localhost:3000/asserts/editor/background1.png",
        x: 0,
        y: 0,
        width: 1300,
        height: 900,
      },
      filters: [],
      className: "Image",
      zIndex: 1,
    },
    overlay: {
      attrs: {
        width: 1300,
        height: 900,
        x: 0,
        y: 0,
      },
      filters: [],
      className: "Rect",
      zIndex: 2,
    },
  },
  shapes: [
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [200, 200, 1100, 200],
        name: "guide",
        stroke: "#fa0000",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 900,
      },
      filters: [],
      className: "Line",
      zIndex: 5,
    },
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [200, 700, 1100, 700],
        name: "guide",
        stroke: "#15ff00",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 900,
      },
      filters: [],
      className: "Line",
      zIndex: 6,
    },
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [224, 225, 1074, 225],
        name: "guide",
        stroke: "#123",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 850,
      },
      filters: [],
      className: "Line",
      zIndex: 7,
    },
    {
      attrs: {
        hitStrokeWidth: 0,
        points: [224, 675, 1074, 675],
        name: "guide",
        stroke: "#4c00ff",
        strokeWidth: 0,
        x: 0,
        y: 0,
        width: 850,
      },
      filters: [],
      className: "Line",
      zIndex: 8,
    },
    {
      attrs: {
        type: "shape",
        x: 649,
        y: 450,
        radius: 50,
        fill: "rgba(255,255,255,1)",
        scaleX: 2.330193125043505,
        scaleY: 2.330193125043505,
        width: 100,
        height: 100,
      },
      filters: [],
      className: "Circle",
      zIndex: 9,
    },
    {
      attrs: {
        x: 596,
        y: 496.51,
        width: 108.56,
        height: 40,
      },
      filters: [],
      className: "Label",
      zIndex: 10,
      children: [
        {
          attrs: {
            width: 108.564453125,
            height: 40,
          },
          className: "Tag",
        },
        {
          attrs: {
            text: "DIGITAL\nEVOLUTION",
            fill: "rgba(255,0,0,1)",
            fontSize: "20",
            fontFamily: "고딕",
            height: "auto",
          },
          className: "Text",
        },
      ],
    },
    {
      attrs: {
        width: 100,
        height: 100,
        x: 577,
        y: 353.5,
        scaleX: 1.4300349646075137,
        scaleY: 1.4300349646075148,
        url: "http://localhost:3000/asserts/editor/clipart/clipart1.png",
      },
      filters: [],
      className: "Image",
      zIndex: 11,
    },
    {
      attrs: {
        x: 200,
        y: 200,
        width: 900,
        height: 500,
        fill: "red",
        name: "bgc",
        hitStrokeWidth: 0,
      },
      filters: [],
      className: "Rect",
      zIndex: 0,
    },
  ],
};
